dataset_path: /Users/ranhomri/tensorleap/data/coco8 # this foldr is expected to contain a json file for each subset and an `images` dir

BATCH_SIZE: 4
TRAIN_SIZE: 4
VAL_SIZE: 4
TEST_SIZE: 4

BACKGROUND_LABEL: 81  # always n_classes + 1
CLASSES: 80  # number of different classes the model was trained on
CONF_THRESH: 0.35  # the minimal confidence for a detection
IMAGE_SIZE: [640, 640]
MAX_BB_PER_IMAGE: 20  # maximal number of object per image
MODEL_FORMAT: inference  # [inference, training]
NMS_THRESH: 0.5
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
BOX_SIZES:
- - - 10
    - 13
  - - 16
    - 30
  - - 33
    - 23
- - - 30
    - 61
  - - 62
    - 45
  - - 59
    - 119
- - - 116
    - 90
  - - 156
    - 198
  - - 373
    - 326